DEFAULT_AMOUNT_DAYS = 7
MATERIAL_DICT = {
    'N30': 'N30',
    'N511': 'N511',
    'N1278': 'N1278',
    'MUTON': 'MUTON',
}
PREFIXES_ART_DICT = {
    'SH': 'SH',
    'SK': 'SK',
    'SN': 'SK',
    'SF': 'SF',
    'J': 'J',
    'MIT': 'MIT',
    'AN': 'MIT',
    'MK': 'MIT',
    'TIE': 'TIE',
    'FATA': 'F',
    'GR': 'GR',
    'LQ3': 'LQ',
    'SOHOCOAT': 'SOHO',
    'TG': 'TG'
}
STRFORMAT_DEFAULT = '%Y-%m-%d'
INITIAL_COLUMNS_DICT = {
    'brand': 'Бренд',
    'subject': 'Предмет',
    'prefix': 'prefix',
    'pattern': 'pattern',
    'material': 'material',
    'article_supplier': 'Артикул поставщика',
    'nmId': 'nmId',
    'new_price': 'new_price',
    'new_discount': 'new_discount',
    'd_disc': 'd_disc',
    'n_discount': 'n_discount',
    'n_delta': 'n_delta',
    'func_discount': 'func_discount',
    'func_delta': 'func_delta',
    'discount': 'discount',
    'outcome-net': 'Маржа-себест.',
    'Маржа-себест./ шт.': 'Маржа-себест./ шт.',
    'outcome': 'Маржа',
    'income-logistic': 'Выручка-Логистика',
    'income': 'Выручка',
    'hold_up': 'Удержания_minus',
    'hold_down': 'Удержания_plus',
    'Ч. Продажа': 'Ч. Продажа',
    'sell': 'Продажа',
    'Ч. Продажа шт./Логистика шт.': 'Ч. Продажа шт./Логистика шт.',
    'pure_sells_qt': 'Ч. Продажа шт.',
    'commission': 'commission',
    'back_qt': 'Возврат, шт.',
    'stock': 'quantityFull',
    'logistics': 'Логистика',
    'logistics_single': 'Логистика. ед',
    'logistics_qt': 'Логистика шт.',
    'storage': 'Хранение',
    'storage_single': 'Хранение.ед',
    'price': 'price',
    'price_disc': 'price_disc',
    'Ср. Ц. Продажа/ед.': 'Ср. Ц. Продажа/ед.',
    'net_cost': 'net_cost',
    'volume': 'volume',
    'quantity_full_sells_qt': 'quantityFull + Продажа, шт.',
    'back': 'Возврат',
    'sells_days': 'Дней в продаже',
    'storagePricePerBarcode': 'storagePricePerBarcode',
    'shareCost': 'shareCost',
    'outcome_net_storage_single': 'Маржа-себест./ шт.',
    'supplier': 'Поставщик',
    'k_is_sell': 'k_is_sell',
    'k_logistic': 'k_logistic',
    'k_net_cost': 'k_net_cost',
    'k_pure_value': 'k_pure_value',
    'k_qt_full': 'k_qt_full',
    'k_rating': 'k_rating',
    'k_dynamic': 'k_dynamic',
    'k_discount': 'k_discount',
    'order_date': 'Дата заказа покупателем',
    'sell_date': 'Дата продажи',
    'raiting': 'Рейтинг',
    'k_norma_revenue': 'k_norma_revenue',
}
DINAMIC_COLUMNS = [
    "Total_Margin",
    "ABC_Category",
    "CV",
    "XYZ_Category",
]
CHOSEN_COLUMNS = [
    "Бренд",
    "Предмет",
    "prefix",
    "pattern",
    "material",
    "Артикул поставщика",
    "nmId",
    "new_price",
    "new_discount",
    "d_disc",
    "n_discount",
    "n_delta",
    "func_discount",
    "func_delta",
    "discount",
    "Маржа-себест.",
    "Маржа-себест./ шт.",
    "Маржа",
    "Выручка-Логистика",
    "Выручка",
    "Удержания_minus",
    "Удержания_plus",
    "Ч. Продажа",
    "Продажа",
    "Ч. Продажа шт./Логистика шт.",
    "Ч. Продажа шт.",
    "commission",
    "Возврат, шт.",
    "quantityFull",
    "Логистика",
    "Логистика. ед",
    "Логистика шт.",
    "Хранение",
    "Хранение.ед",
    "price",
    "price_disc",
    "Ср. Ц. Продажа/ед.",
    "net_cost",
    "volume",
    "quantityFull + Продажа, шт.",
    "Возврат",
    "Дней в продаже",
    "storagePricePerBarcode",
    "shareCost",
    "Маржа-себест./ шт.",
    "Поставщик",
    "k_is_sell",
    "k_logistic",
    "k_net_cost",
    "k_pure_value",
    "k_qt_full",
    "k_rating",
    "k_discount",
    "openCardCount",
    "addToCartCount",
    "ordersCount",
    "ordersSumRub",
    "buyoutsCount",
    "buyoutsSumRub",
    "cancelCount",
    "cancelSumRub",
    "avgOrdersCountPerDay",
    "avgPriceRub",
    "addToCartPercent",
    "cartToOrderPercent",
    "buyoutsPercent",
    "Total_Margin",
    "ABC_Category",
    "CV",
    "XYZ_Category",
    "ABC_discount",
    "CV_discount",
    "ABC_CV_discount",

]
