"""empty message

Revision ID: 150c35ad470b
Revises: 7e291e74ddd6
Create Date: 2022-06-01 02:36:13.527541

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '150c35ad470b'
down_revision = '7e291e74ddd6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('yandex_disk_token', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'yandex_disk_token')
    # ### end Alembic commands ###
