"""empty message

Revision ID: 3c9c869dc7ef
Revises: 5c5c8bb8ad1f
Create Date: 2022-04-26 16:12:17.964063

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3c9c869dc7ef'
down_revision = '5c5c8bb8ad1f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'goods', ['art'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'goods', type_='unique')
    # ### end Alembic commands ###
