"""empty message

Revision ID: 477046d176ff
Revises: 1a815d8df732
Create Date: 2022-06-11 01:59:56.133178

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '477046d176ff'
down_revision = '1a815d8df732'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('yandex_link', sa.String(length=1000), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'yandex_link')
    # ### end Alembic commands ###
