"""empty message

Revision ID: 57e586623f79
Revises: df66fdc7bb9d
Create Date: 2022-06-09 17:33:10.789226

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '57e586623f79'
down_revision = 'df66fdc7bb9d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('user_email', sa.String(length=100), nullable=True))
    op.drop_column('users', 'email')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('email', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.drop_column('users', 'user_email')
    # ### end Alembic commands ###
