"""empty message

Revision ID: 5c5c8bb8ad1f
Revises: a1f6e1fb87f1
Create Date: 2022-04-26 15:55:51.741395

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5c5c8bb8ad1f'
down_revision = 'a1f6e1fb87f1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('goods',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('art', sa.String(length=80), nullable=True),
    sa.Column('net_cost', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('goods')
    # ### end Alembic commands ###
