"""empty message

Revision ID: 7a87eb6071f0
Revises: 6e235b4ad9a6
Create Date: 2022-04-27 22:37:32.278621

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7a87eb6071f0'
down_revision = '6e235b4ad9a6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_temp_table_index', table_name='temp_table')
    op.drop_table('temp_table')
    op.drop_constraint('products_article_key', 'products', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('products_article_key', 'products', ['article'])
    op.create_table('temp_table',
    sa.Column('index', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('company_id', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('article', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('net_cost', sa.BIGINT(), autoincrement=False, nullable=True)
    )
    op.create_index('ix_temp_table_index', 'temp_table', ['index'], unique=False)
    # ### end Alembic commands ###
