"""empty message

Revision ID: 81a8fdb41d22
Revises: 115849583581
Create Date: 2022-09-05 14:50:18.576515

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '81a8fdb41d22'
down_revision = '115849583581'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('is_private', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transactions', 'is_private')
    # ### end Alembic commands ###
