"""empty message

Revision ID: 8af530b18241
Revises: 412b1eab031d
Create Date: 2022-09-05 15:18:13.049104

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8af530b18241'
down_revision = '412b1eab031d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('is_private', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transactions', 'is_private')
    # ### end Alembic commands ###
