"""empty message

Revision ID: a1f6e1fb87f1
Revises: af9abc35dd9c
Create Date: 2022-04-26 00:44:12.643680

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a1f6e1fb87f1'
down_revision = 'af9abc35dd9c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('initial_file_path', sa.String(length=500), nullable=True))
    op.drop_column('users', 'initial_fil_path')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('initial_fil_path', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    op.drop_column('users', 'initial_file_path')
    # ### end Alembic commands ###
