"""empty message

Revision ID: a88c79b08ed5
Revises: 3c9c869dc7ef
Create Date: 2022-04-26 17:46:11.709781

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a88c79b08ed5'
down_revision = '3c9c869dc7ef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('goods', sa.Column('id', sa.Integer(), nullable=False))
    op.create_unique_constraint(None, 'goods', ['article'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'goods', type_='unique')
    op.drop_column('goods', 'id')
    # ### end Alembic commands ###
