"""empty message

Revision ID: af9abc35dd9c
Revises: fbee8676472e
Create Date: 2022-04-26 00:35:10.695513

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'af9abc35dd9c'
down_revision = 'fbee8676472e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('initial_fil_path', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'initial_fil_path')
    # ### end Alembic commands ###
