"""empty message

Revision ID: be3574bfe804
Revises: 8af530b18241
Create Date: 2022-09-05 15:30:38.601970

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'be3574bfe804'
down_revision = '8af530b18241'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('is_private', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transactions', 'is_private')
    # ### end Alembic commands ###
