"""empty message

Revision ID: bf8bad0ed054
Revises: 8aab62b445c4
Create Date: 2022-06-04 23:42:19.476781

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bf8bad0ed054'
down_revision = '8aab62b445c4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('yandex_link', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transactions', 'yandex_link')
    # ### end Alembic commands ###
