"""empty message

Revision ID: c822bc997cd1
Revises: eeac66df4afe
Create Date: 2022-04-27 16:26:39.568029

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c822bc997cd1'
down_revision = 'eeac66df4afe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('products',
    sa.Column('article', sa.String(length=80), nullable=False),
    sa.Column('net_cost', sa.Integer(), nullable=True),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('article'),
    sa.UniqueConstraint('article')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('products')
    # ### end Alembic commands ###
