"""empty message

Revision ID: d8ecccfcebd5
Revises: be3574bfe804
Create Date: 2022-09-05 15:31:16.678693

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'd8ecccfcebd5'
down_revision = 'be3574bfe804'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('is_private', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transactions', 'is_private')
    # ### end Alembic commands ###
