"""empty message

Revision ID: fbee8676472e
Revises: d79c3989ef1a
Create Date: 2022-04-22 22:26:27.868245

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fbee8676472e'
down_revision = 'd79c3989ef1a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('initial_sum', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'initial_sum')
    # ### end Alembic commands ###
